public class Question4 {
    public static void main(String[] args) {
        try {
            int result = 10/0;
        } catch (Throwable e) {
            System.out.println("Caught exception: " + e.getMessage());
        }
    }
}
